-- =========================================================
-- MIGRASI NILAI LAMA -> tabel public.nilai
-- Jalankan file ini SETELAH semua akun siswa berhasil dibuat
-- (lewat menu "Buat Akun Siswa" di dashboard guru, pakai
-- MIGRASI_AKUN_SISWA.txt), karena migrasi ini mencocokkan
-- siswa berdasarkan kolom username di profiles.
-- =========================================================

insert into public.nilai (siswa_id, jenis, skor, skor_asli, predikat)
select p.id, v.jenis, v.skor, v.skor_asli, v.predikat
from (values
('allfin', 'Latihan Ulangan Harian 1', 80.0, null, 'B'),
('amanatun', 'Latihan Ulangan Harian 1', 74.0, null, 'C'),
('anggita', 'Latihan Ulangan Harian 1', 67.0, null, 'D'),
('anisa', 'Latihan Ulangan Harian 1', 48.0, null, 'D'),
('aqila', 'Latihan Ulangan Harian 1', 76.0, null, 'C'),
('azah', 'Latihan Ulangan Harian 1', 76.0, null, 'C'),
('azqiatul', 'Latihan Ulangan Harian 1', 91.0, null, 'A'),
('azriel', 'Latihan Ulangan Harian 1', 89.0, null, 'B'),
('bagus', 'Latihan Ulangan Harian 1', null, null, '-'),
('bening', 'Latihan Ulangan Harian 1', 54.0, null, 'D'),
('dewi', 'Latihan Ulangan Harian 1', 85.0, null, 'B'),
('fatih', 'Latihan Ulangan Harian 1', 52.0, null, 'D'),
('fina', 'Latihan Ulangan Harian 1', 54.0, null, 'D'),
('fithriyah', 'Latihan Ulangan Harian 1', 48.0, null, 'D'),
('giska', 'Latihan Ulangan Harian 1', 87.0, null, 'B'),
('hasnah', 'Latihan Ulangan Harian 1', 54.0, null, 'D'),
('ika', 'Latihan Ulangan Harian 1', 59.0, null, 'D'),
('ikhsan', 'Latihan Ulangan Harian 1', 72.0, null, 'C'),
('iman', 'Latihan Ulangan Harian 1', 65.0, null, 'D'),
('inayah', 'Latihan Ulangan Harian 1', 94.0, null, 'A'),
('kanza', 'Latihan Ulangan Harian 1', 72.0, null, 'C'),
('kirani', 'Latihan Ulangan Harian 1', 78.0, null, 'C'),
('muhammad', 'Latihan Ulangan Harian 1', 56.0, null, 'D'),
('myiesha', 'Latihan Ulangan Harian 1', 89.0, null, 'B'),
('nesi', 'Latihan Ulangan Harian 1', 59.0, null, 'D'),
('nirina', 'Latihan Ulangan Harian 1', 54.0, null, 'D'),
('nisa', 'Latihan Ulangan Harian 1', 44.0, null, 'D'),
('nurul', 'Latihan Ulangan Harian 1', 74.0, null, 'C'),
('putri', 'Latihan Ulangan Harian 1', 78.0, null, 'C'),
('qonita', 'Latihan Ulangan Harian 1', 87.0, null, 'B'),
('rida', 'Latihan Ulangan Harian 1', 67.0, null, 'D'),
('salsahbila', 'Latihan Ulangan Harian 1', 98.0, null, 'A'),
('wahidah', 'Latihan Ulangan Harian 1', 57.0, null, 'D'),
('zulfa', 'Latihan Ulangan Harian 1', 70.0, null, 'C'),
('fianalucugemoibaik', 'Latihan Ulangan Harian - Describing People', 81.0, 81.0, 'B'),
('mandarizkyzakya', 'Latihan Ulangan Harian - Describing People', 78.0, 78.0, 'C'),
('syifaa', 'Latihan Ulangan Harian - Describing People', null, null, '-'),
('aurelianurulh_767', 'Latihan Ulangan Harian - Describing People', 89.0, 89.0, 'B'),
('azzadacantikmasyaallah', 'Latihan Ulangan Harian - Describing People', 50.0, 80.0, 'D'),
('bimagantengbgtxk', 'Latihan Ulangan Harian - Describing People', 76.0, 76.0, 'C'),
('haiilesta', 'Latihan Ulangan Harian - Describing People', 56.0, 56.0, 'D'),
('destriazahra48', 'Latihan Ulangan Harian - Describing People', 74.0, 74.0, 'C'),
('efi', 'Latihan Ulangan Harian - Describing People', 56.0, 56.0, 'D'),
('erniavizahro', 'Latihan Ulangan Harian - Describing People', 85.0, 89.0, 'B'),
('fajriana15', 'Latihan Ulangan Harian - Describing People', 65.0, 69.0, 'D'),
('ficoganteng', 'Latihan Ulangan Harian - Describing People', null, null, '-'),
('hervinana', 'Latihan Ulangan Harian - Describing People', 74.0, 74.0, 'C'),
('ikamelin', 'Latihan Ulangan Harian - Describing People', 81.0, 81.0, 'B'),
('ilhamgantengbangetmiripjefrinichol', 'Latihan Ulangan Harian - Describing People', 46.0, 46.0, 'D'),
('justinemuhammad', 'Latihan Ulangan Harian - Describing People', 83.0, 83.0, 'B'),
('kasih', 'Latihan Ulangan Harian - Describing People', 74.0, 74.0, 'C'),
('laela04', 'Latihan Ulangan Harian - Describing People', 61.0, 61.0, 'D'),
('linawijia', 'Latihan Ulangan Harian - Describing People', 63.0, 63.0, 'D'),
('listi13', 'Latihan Ulangan Harian - Describing People', null, null, '-'),
('l,lyaa', 'Latihan Ulangan Harian - Describing People', 46.0, 46.0, 'D'),
('maznahz', 'Latihan Ulangan Harian - Describing People', 70.0, 85.0, 'C'),
('muhammad ilyasa', 'Latihan Ulangan Harian - Describing People', 69.0, 80.0, 'D'),
('multazimatunkeren', 'Latihan Ulangan Harian - Describing People', 67.0, 67.0, 'D'),
('mutia', 'Latihan Ulangan Harian - Describing People', 54.0, 54.0, 'D'),
('naila123', 'Latihan Ulangan Harian - Describing People', 76.0, 76.0, 'C'),
('novelnovel04', 'Latihan Ulangan Harian - Describing People', 61.0, 61.0, 'D'),
('nitazein', 'Latihan Ulangan Harian - Describing People', 74.0, 81.0, 'C'),
('finabukanvina', 'Latihan Ulangan Harian - Describing People', 85.0, 85.0, 'B'),
('renifazira', 'Latihan Ulangan Harian - Describing People', 83.0, 83.0, 'B'),
('rizqikiyania01', 'Latihan Ulangan Harian - Describing People', 74.0, 81.0, 'C'),
('haiicaa', 'Latihan Ulangan Harian - Describing People', 91.0, 91.0, 'A'),
('sarah.az', 'Latihan Ulangan Harian - Describing People', 81.0, 81.0, 'B'),
('shafa0811', 'Latihan Ulangan Harian - Describing People', 70.0, 70.0, 'C'),
('taufiqkalcerabiz', 'Latihan Ulangan Harian - Describing People', 48.0, 48.0, 'D'),
('aghna.rh', 'Latihan Ulangan Harian 1 - Describing People', 72.0, 72.0, 'C'),
('alfinaa', 'Latihan Ulangan Harian 1 - Describing People', 54.0, 61.0, 'D'),
('liaa', 'Latihan Ulangan Harian 1 - Describing People', null, null, '-'),
('lasilaz', 'Latihan Ulangan Harian 1 - Describing People', 65.0, 65.0, 'D'),
('barraaumarr777', 'Latihan Ulangan Harian 1 - Describing People', 69.0, 76.0, 'D'),
('citra', 'Latihan Ulangan Harian 1 - Describing People', 61.0, 61.0, 'D'),
('erinaoktaviani1211', 'Latihan Ulangan Harian 1 - Describing People', 54.0, 54.0, 'D'),
('eeuuiiss', 'Latihan Ulangan Harian 1 - Describing People', 61.0, 61.0, 'D'),
('hanzzbaekk', 'Latihan Ulangan Harian 1 - Describing People', 63.0, 67.0, 'D'),
('fatihahramadani37', 'Latihan Ulangan Harian 1 - Describing People', 80.0, 80.0, 'B'),
('fncrsa', 'Latihan Ulangan Harian 1 - Describing People', 50.0, 72.0, 'D'),
('hafizzah25', 'Latihan Ulangan Harian 1 - Describing People', 61.0, 61.0, 'D'),
('heni_nur_aida', 'Latihan Ulangan Harian 1 - Describing People', 67.0, 67.0, 'D'),
('herwinachellesth', 'Latihan Ulangan Harian 1 - Describing People', 69.0, 69.0, 'D'),
('liliimutttt', 'Latihan Ulangan Harian 1 - Describing People', 72.0, 72.0, 'C'),
('putzzx', 'Latihan Ulangan Harian 1 - Describing People', 91.0, 91.0, 'A'),
('khanzameilanix-J615', 'Latihan Ulangan Harian 1 - Describing People', 57.0, 57.0, 'D'),
('awalia', 'Latihan Ulangan Harian 1 - Describing People', 70.0, 70.0, 'C'),
('linzz', 'Latihan Ulangan Harian 1 - Describing People', 59.0, 59.0, 'D'),
('phosphophyllite', 'Latihan Ulangan Harian 1 - Describing People', 98.0, 98.0, 'A'),
('mumud', 'Latihan Ulangan Harian 1 - Describing People', 63.0, 63.0, 'D'),
('nadif', 'Latihan Ulangan Harian 1 - Describing People', 72.0, 72.0, 'C'),
('amania', 'Latihan Ulangan Harian 1 - Describing People', 78.0, 78.0, 'C'),
('paalllzzz', 'Latihan Ulangan Harian 1 - Describing People', 52.0, 56.0, 'D'),
('nissa223', 'Latihan Ulangan Harian 1 - Describing People', 65.0, 65.0, 'D'),
('putrianjanix-j312', 'Latihan Ulangan Harian 1 - Describing People', 61.0, 61.0, 'D'),
('whylin', 'Latihan Ulangan Harian 1 - Describing People', 85.0, 89.0, 'B'),
('amandaputr1', 'Latihan Ulangan Harian 1 - Describing People', 67.0, 67.0, 'D'),
('dyannn', 'Latihan Ulangan Harian 1 - Describing People', 59.0, 59.0, 'D'),
('deskiaa', 'Latihan Ulangan Harian 1 - Describing People', 83.0, 83.0, 'B'),
('callysaa', 'Latihan Ulangan Harian 1 - Describing People', 87.0, 87.0, 'B'),
('septianyusuf777', 'Latihan Ulangan Harian 1 - Describing People', 74.0, 74.0, 'C'),
('lucifer', 'Latihan Ulangan Harian 1 - Describing People', 76.0, 76.0, 'C'),
('awaann', 'Latihan Ulangan Harian 1 - Describing People', 69.0, 69.0, 'D'),
('adinda', 'Ulangan Harian 1 - Narrative Text Legend', 84.73, null, 'B'),
('afrilia', 'Ulangan Harian 1 - Narrative Text Legend', 73.28, null, 'C'),
('ajeng', 'Ulangan Harian 1 - Narrative Text Legend', 79.39, null, 'C'),
('aleysia', 'Ulangan Harian 1 - Narrative Text Legend', 37.02, null, 'D'),
('ana', 'Ulangan Harian 1 - Narrative Text Legend', 61.07, null, 'D'),
('anisa', 'Ulangan Harian 1 - Narrative Text Legend', 72.52, null, 'C'),
('anita', 'Ulangan Harian 1 - Narrative Text Legend', 56.0, null, 'D'),
('aqilla', 'Ulangan Harian 1 - Narrative Text Legend', 79.77, null, 'C'),
('arfania', 'Ulangan Harian 1 - Narrative Text Legend', 76.34, null, 'C'),
('asyifa', 'Ulangan Harian 1 - Narrative Text Legend', 72.52, null, 'C'),
('cerrel', 'Ulangan Harian 1 - Narrative Text Legend', 57.25, null, 'D'),
('dinna', 'Ulangan Harian 1 - Narrative Text Legend', 52.67, null, 'D'),
('edy', 'Ulangan Harian 1 - Narrative Text Legend', 71.76, null, 'C'),
('elma', 'Ulangan Harian 1 - Narrative Text Legend', 96.18, null, 'A'),
('fadhilah', 'Ulangan Harian 1 - Narrative Text Legend', 74.81, null, 'C'),
('falen', 'Ulangan Harian 1 - Narrative Text Legend', 74.0, null, '  C'),
('fida', 'Ulangan Harian 1 - Narrative Text Legend', 92.37, null, 'A'),
('gandis', 'Ulangan Harian 1 - Narrative Text Legend', 41.0, null, 'D'),
('ikhsan', 'Ulangan Harian 1 - Narrative Text Legend', 76.34, null, 'C'),
('irma', 'Ulangan Harian 1 - Narrative Text Legend', 88.55, null, 'B'),
('khansa', 'Ulangan Harian 1 - Narrative Text Legend', 77.1, null, 'C'),
('kukuh', 'Ulangan Harian 1 - Narrative Text Legend', 83.59, null, 'B'),
('laura', 'Ulangan Harian 1 - Narrative Text Legend', 96.18, null, 'A'),
('maharani', 'Ulangan Harian 1 - Narrative Text Legend', 84.35, null, 'B'),
('nabila', 'Ulangan Harian 1 - Narrative Text Legend', 67.56, null, 'D'),
('nandi', 'Ulangan Harian 1 - Narrative Text Legend', 67.94, null, 'D'),
('neiza', 'Ulangan Harian 1 - Narrative Text Legend', 87.02, null, 'B'),
('nur', 'Ulangan Harian 1 - Narrative Text Legend', 96.18, null, 'A'),
('revina', 'Ulangan Harian 1 - Narrative Text Legend', 80.15, null, 'B'),
('rifan', 'Ulangan Harian 1 - Narrative Text Legend', 75.19, null, 'C'),
('rizki', 'Ulangan Harian 1 - Narrative Text Legend', 79.39, null, 'C'),
('roisyah', 'Ulangan Harian 1 - Narrative Text Legend', 64.12, null, 'D'),
('septiana', 'Ulangan Harian 1 - Narrative Text Legend', 72.9, null, 'C'),
('tiara', 'Ulangan Harian 1 - Narrative Text Legend', 87.02, null, 'B'),
('wiwit', 'Ulangan Harian 1 - Narrative Text Legend', 84.35, null, 'B'),
('yohana', 'Ulangan Harian 1 - Narrative Text Legend', 71.76, null, 'C'),
('adelia', 'Ulangan Harian 1 - Narrative Text Legend', 53.59, null, 'D'),
('afnan', 'Ulangan Harian 1 - Narrative Text Legend', 56.15, null, 'D'),
('alifia', 'Ulangan Harian 1 - Narrative Text Legend', 58.72, null, 'D'),
('andika', 'Ulangan Harian 1 - Narrative Text Legend', 71.54, null, 'C'),
('anggi', 'Ulangan Harian 1 - Narrative Text Legend', 71.54, null, 'C'),
('anna', 'Ulangan Harian 1 - Narrative Text Legend', 82.0, null, 'B'),
('assyifau', 'Ulangan Harian 1 - Narrative Text Legend', 99.74, null, 'A'),
('cahya', 'Ulangan Harian 1 - Narrative Text Legend', 53.59, null, 'D'),
('citra', 'Ulangan Harian 1 - Narrative Text Legend', 66.41, null, 'D'),
('desi', 'Ulangan Harian 1 - Narrative Text Legend', 74.1, null, 'C'),
('diana', 'Ulangan Harian 1 - Narrative Text Legend', 74.1, null, 'C'),
('dina', 'Ulangan Harian 1 - Narrative Text Legend', 66.41, null, 'D'),
('elza', 'Ulangan Harian 1 - Narrative Text Legend', 56.15, null, 'D'),
('faiq', 'Ulangan Harian 1 - Narrative Text Legend', 76.67, null, 'C'),
('fikri', 'Ulangan Harian 1 - Narrative Text Legend', 100.0, null, 'A'),
('julia', 'Ulangan Harian 1 - Narrative Text Legend', 61.28, null, 'D'),
('khairunisa', 'Ulangan Harian 1 - Narrative Text Legend', 94.62, null, 'A'),
('lusiana', 'Ulangan Harian 1 - Narrative Text Legend', 45.9, null, 'D'),
('mega', 'Ulangan Harian 1 - Narrative Text Legend', 66.41, null, 'D'),
('melisa', 'Ulangan Harian 1 - Narrative Text Legend', 63.85, null, 'D'),
('mussyarofatul', 'Ulangan Harian 1 - Narrative Text Legend', 68.97, null, 'D'),
('nadira', 'Ulangan Harian 1 - Narrative Text Legend', 100.0, null, 'A'),
('naisya', 'Ulangan Harian 1 - Narrative Text Legend', 61.28, null, 'D'),
('nanda', 'Ulangan Harian 1 - Narrative Text Legend', 71.54, null, 'C'),
('niken', 'Ulangan Harian 1 - Narrative Text Legend', 76.67, null, 'C'),
('novita', 'Ulangan Harian 1 - Narrative Text Legend', 61.28, null, 'D'),
('putri', 'Ulangan Harian 1 - Narrative Text Legend', 66.41, null, 'D'),
('qianu', 'Ulangan Harian 1 - Narrative Text Legend', 79.23, null, 'C'),
('regita', 'Ulangan Harian 1 - Narrative Text Legend', 86.92, null, 'B'),
('rezky', 'Ulangan Harian 1 - Narrative Text Legend', 81.79, null, 'B'),
('rifda', 'Ulangan Harian 1 - Narrative Text Legend', 53.59, null, 'D'),
('shaleha', 'Ulangan Harian 1 - Narrative Text Legend', 53.59, null, 'D'),
('shinta', 'Ulangan Harian 1 - Narrative Text Legend', 61.28, null, 'D'),
('syela', 'Ulangan Harian 1 - Narrative Text Legend', 71.54, null, 'C'),
('vitaliya', 'Ulangan Harian 1 - Narrative Text Legend', 94.62, null, 'A'),
('wahyu', 'Ulangan Harian 1 - Narrative Text Legend', 81.79, null, 'B'),
('adzkiya', 'Ulangan Harian 1', 48.72, null, 'D'),
('ainina', 'Ulangan Harian 1', 89.74, null, 'B'),
('ajizah', 'Ulangan Harian 1', 69.23, null, 'D'),
('alkhila', 'Ulangan Harian 1', 53.85, null, 'D'),
('anggraini', 'Ulangan Harian 1', 66.67, null, 'D'),
('anita', 'Ulangan Harian 1', 69.23, null, 'D'),
('antika', 'Ulangan Harian 1', null, null, '-'),
('ariqah', 'Ulangan Harian 1', 92.31, null, 'A'),
('aulia', 'Ulangan Harian 1', 76.92, null, 'C'),
('azam', 'Ulangan Harian 1', 53.58, null, 'D'),
('dewi', 'Ulangan Harian 1', 79.49, null, 'C'),
('eka', 'Ulangan Harian 1', 79.49, null, 'C'),
('erna', 'Ulangan Harian 1', 79.49, null, 'C'),
('fadilah', 'Ulangan Harian 1', 89.74, null, 'B'),
('fajri', 'Ulangan Harian 1', 79.49, null, 'C'),
('fanesia', 'Ulangan Harian 1', 41.03, null, 'D'),
('faradilla', 'Ulangan Harian 1', 71.79, null, 'C'),
('farah', 'Ulangan Harian 1', null, null, '-'),
('fransiska', 'Ulangan Harian 1', 76.92, null, 'C'),
('gendhis', 'Ulangan Harian 1', 69.23, null, 'D'),
('juneti', 'Ulangan Harian 1', 69.23, null, 'D'),
('laelatul', 'Ulangan Harian 1', 74.36, null, 'C'),
('lulu', 'Ulangan Harian 1', 58.97, null, 'D'),
('melina', 'Ulangan Harian 1', 71.79, null, 'C'),
('nabila', 'Ulangan Harian 1', 28.21, null, 'D'),
('nova', 'Ulangan Harian 1', 38.46, null, 'D'),
('rafi', 'Ulangan Harian 1', 53.85, null, 'D'),
('renaya', 'Ulangan Harian 1', 43.59, null, 'D'),
('rizka', 'Ulangan Harian 1', 56.41, null, 'D'),
('roidatul', 'Ulangan Harian 1', 48.72, null, 'D'),
('salsabilla', 'Ulangan Harian 1', 79.49, null, 'C'),
('syahwa', 'Ulangan Harian 1', 79.49, null, 'C'),
('triyana', 'Ulangan Harian 1', 51.28, null, 'D'),
('yonareta', 'Ulangan Harian 1', 61.54, null, 'D'),
('zadit', 'Ulangan Harian 1', 46.15, null, 'D')
) as v(username, jenis, skor, skor_asli, predikat)
join public.profiles p on p.username = v.username;
